name: Run tests

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-16.04
    
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    # Checkout do codigo do projeto
      - uses: actions/checkout/@v2
      
      # Setup do Node.JS
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{matrix.node-version}}
      
      # Instalando as dependencias
      - run: npm install
      
      # Executando os testes 
      - run: npm run test

      - name: Upload a screenshots
        uses: actions/upload-artifact@v2.2.0
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
          
      - name: Upload videos
        uses: actions/upload-artifact@v2.2.0
        if: always()
        with:
          name: videos
          path: web/cypress/videos
